spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: utf-8
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  config:
    import: classpath:oauth.yml

logging.level:
  org.hibernate.SQL: debug
